  language: python
  python:
    - "3.6"
  script:
    - pytest
  install:
  - pip install -r requirements.txt

dist: trusty
sudo: required

addons:
  sonarcloud:
    organization: rapx3-github
    token:
      secure: ${SONAR_TOKEN}
jdk:
  - oraclejdk8
script:
  - sonar-scanner
cache:
  directories:
    - '$HOME/.sonar/cache'